### ISSUE TITLE
Add new maintainers

### ISSUE THREAD

**Issue by depuits** [dib0/elro_connects#30]
I noticed that simple pull request can take a while before they are merged. I understand you probably have other obligations and priorities so it might be of interest for the project to add some new maintainers so that updates can be merged and published faster. I for one volunteer myself as maintainer. I don't have the best python skills but I now actively use the project and know enough to help fix any issues and review changes. @Skons might also be interested based on his recent pull requests.

**Comment by depuits** [comment]
@hildensia and @dib0 any news on this?

**Comment by dib0** [comment]
Hi @depuits ,

I've added you as a maintainer. @Skons if you are interested, please let me know, I'll add you too.

**Comment by dib0** [comment]
@Skons  Thanks! I've added you as a collaborator.
