### ISSUE TITLE
Reworked api library

### ISSUE THREAD

**Issue by jbouwh** [dib0/elro_connects#39]
I've done some rework om the code and created an API. I'm thinking of creating a direct integration for Home Assistant.
I omitted the MQTT part, and added some sample code. I'm not using the get macaddress stuff here.
Have look at:
https://github.com/jbouwh/lib-elro-connects

**Comment by depuits** [comment]
This looks nice. I'm not sure if this project should actually use this a dependency and the be more focused on the mqtt interface part or if both projects can just look at each other for improvements. If we would use the library as a base then we should create an organization to bundle the repositories and to provide maintainer access to everyone currently involved.

**Comment by jbouwh** [comment]
I agree. My plan is to start this parallel. I am working on an integration for Home Assistant.
I have no experience setting up an organization, we also could start this later, feel free to contribute. The library installs with pip install lib-elro-connects. It requires python 3.9 as a minimum requirement. When deploying using a Docker container this won't be an issue.
