### ISSUE TITLE
Send commands using CLI and/or mqtt

### ISSUE THREAD

**Issue by depuits** [dib0/elro_connects#7]
It would be nice if there would be an option to send commands using the CLI or an mqtt message. This for example to change the device names or testing alarms. 

For the CLI it could be something like
```
# Connect to controller and send mqtt messages 
elro connect -k HOSTNAME -i ID -m "mqtt://username:password@host.domain"

# Change device name using -a (action) flag
elro device -k HOSTNAME -i ID -d "Device name" -a CHANGE_NAME "new device name"

# Test device alarm
elro device -k HOSTNAME -i ID -d "Device name" -a TEST_ALARM
```

Another option would be to use mqtt messages using following topic
```
[base_topic]/elro/[device_name_or_id]/action
```
with a json object as message
```
{
    "action": "change_name",
    "newName": "new device name"
}
```

Using the CLI route it would probably be interesting to have a config file for the connection options so you don't have to repeat these for every action. This is something that's not required when using mqtt action messages.

**Comment by hildensia** [comment]
Good idea, I'll look into the protocol if that's possible

**Comment by depuits** [comment]
Are there any more action which are not possible after the last pull request was merged? Otherwise this issue can be closed.
